---
title: blog-post-8
author: Daniel Sussman
date: '2022-12-09'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-12-09T22:41:44-05:00'
featuredVideo: ~
featuredImage: ~
---


Our tentative thesis is that the global temperature will increase as CO2 emission and year increasing. We already found the relationship between year and temperature, also the relationship between CO2 emission and temperature. We use our data to draw the figure of years and CO2 emission. It is found that with the increase of years, co2 emission also increased. Then we also draw the plot and find that CO2 emission is also directly proportional to the weather which can convince our thesis. Therefore, we can finally get: as the years increase, the co2 emissions increase, resulting in an increase in temperature. Moreover, we use other data and find the year still appears to be positively proportional to the average change in temperature of the world, which again confirms our tentative thesis about the relationship between year and temperature.


For our planning of polishing the visualizations and tables, we are going to give “temperature” for the title, which is our theme. For the Explanation part, we're going to use a smaller font. Briefly introduce our thesis and our analysis of this thesis in language that the audience can understand. The explanation of this Thesis is what I have above. The content of the analysis will be extracted from the analysis page and relayed into easy-to-understand content. We haven't finished this section yet, but we've written a little bit like:  We want to test various variables such as "Year", "Regions", "CO2 emission", "Coal", "Gas", "population", forest area, and Oil; In order to get the relationship between year and temperature, we first draw the figure of years and CO2 emission. (Use these words to briefly introduce each of our figures to the public.)  After watching the website https://gallery.htmlwidgets.org/, we find our figures look boring to the public because more of them have no color. And the information in them is not easily visible. We decide to make our figures more colorful and easier for people to find the relationship. Also, we will make our figures more variable.

